### ISSUE TITLE
[Bug] single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by Zerohertz** [Zerohertz/awesome-jmy#3]
## 내용

![image](https://github.com/Zerohertz/awesome-jmy/assets/42334717/0bbafbd0-5989-479c-8a04-ecf450f77b27)

이상하게 `python src/vis.py`에서는 정상적 실행이 되지만, `python main.py`에서는 에러가 발생한다.

+ [오류 X](https://github.com/Zerohertz/awesome-jmy/actions/runs/6069242412/job/16463360452)
+ [오류 O](https://github.com/Zerohertz/awesome-jmy/actions/runs/6069417434/job/16463784481)

## 작업 내용

- [x] 원인 파악
- [x] 문제 해결

**Comment by Zerohertz** [comment]
`single positional indexer is out-of-bounds` 오류는 Pandas 라이브러리를 사용할 때 주로 발생하며, 일반적으로 인덱싱 작업 중에 지정한 인덱스가 데이터 프레임이나 시리즈의 유효한 범위를 벗어났을 때 나타납니다. 이러한 오류는 다음과 같은 상황에서 일반적으로 발생합니다:

1. **DataFrame 또는 Series 인덱싱**: 유효한 범위를 벗어나는 위치의 데이터를 참조하려고 할 때.

    ```python
    import pandas as pd
    df = pd.DataFrame({'A': [1, 2, 3]})
    print(df.loc[3])  # df에는 0, 1, 2 인덱스만 있으므로, 3은 범위를 벗어납니다.
    ```

2. **iloc, loc 사용 시**: iloc나 loc 함수를 사용하여 인덱스가 DataFrame 또는 Series의 크기보다 큰 값을 사용할 때.

    ```python
    s = pd.Series([1, 2, 3])
    print(s.iloc[3])  # 유효한 인덱스는 0, 1, 2이므로 3은 범위를 벗어납니다.
    ```

3. **슬라이싱 이슈**: 슬라이싱의 시작과 끝 인덱스가 범위를 벗어나는 경우에도 이 오류가 발생할 수 있습니다.

이러한 오류를 해결하려면:

- 인덱스가 유효한 범위 내에 있는지 확인하세요.
- DataFrame이나 Series가 비어있지 않은지 확인하세요.
- 필요한 경우, 데이터의 길이를 확인하여 인덱싱 작업을 수행하세요.

```python
# 데이터 길이 확인
len(df)
```

인덱스가 유효한 범위 내에 있는지 확인하고 코드를 수정하여 이 문제를 해결할 수 있습니다.

**Comment by Zerohertz** [comment]
```python
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    vd.plot_time()
  File "/home/zerohertz/Zerohertz/test/src/vis.py", line 190, in plot_time
    self._twin_plot(time_data, name)
  File "/home/zerohertz/Zerohertz/test/src/vis.py", line 217, in _twin_plot
    m = self.data[self.data["업체명"] == name]["현역 배정인원"].iloc[0]
  File "/home/zerohertz/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/zerohertz/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1501, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/zerohertz/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1444, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

`time.tsv`에 데이터를 적재하면서 `현역 배정인원`을 가져올 때 기업이 사라지면 오류가 발생하는 것을 확인했다.

**Comment by Zerohertz** [comment]
```python
        try:
            m = self.data[self.data["업체명"] == name]["현역 배정인원"].iloc[0]
            plt.title(f"{name} (현역 배정인원: {m}명)")
        except:
            plt.title(f"{name} (현역 배정인원: X)")
```

예외문으로 해결
